[[redirects]]
   from = "/api/*"
   to = "https://xp-bar-backend.herokuapp.com/api/:splat"
   status = 200
   force = true
   headers = {X-From = "Netlify"}

   [[redirects]]
      from = "/xp-bar/*"
      to = "/index.html"
      status = 200